// Definiciones de temas - Deben coincidir con ThemeService.ts en main
export const themeDefinitions = {
  dark: {
    '--primary': '#DE350D',
    '--primary-dark': '#B22A0A',
    '--accent': '#6347FF',
    '--accent-light': '#8B6FFF',
    '--bg-dark': '#0D0D0D',
    '--bg-card': '#161616',
    '--bg-surface': '#1E1E1E',
    '--text-primary': '#FFFFFF',
    '--text-secondary': '#A0A0A0',
    '--success': '#2ED573',
    '--warning': '#FFA502',
    '--error': '#FF4757',
    '--border': '#2A2A2A',
  },
  light: {
    '--primary': '#DE350D',
    '--primary-dark': '#B22A0A',
    '--accent': '#6347FF',
    '--accent-light': '#8B6FFF',
    '--bg-dark': '#F5F5F5',
    '--bg-card': '#FFFFFF',
    '--bg-surface': '#EEEEEE',
    '--text-primary': '#1A1A1A',
    '--text-secondary': '#6B6B6B',
    '--success': '#27AE60',
    '--warning': '#E67E22',
    '--error': '#E74C3C',
    '--border': '#D0D0D0',
  },
  'roblox-classic': {
    '--primary': '#DE350D',
    '--primary-dark': '#B22A0A',
    '--accent': '#FFAB00',
    '--accent-light': '#FFC400',
    '--bg-dark': '#111111',
    '--bg-card': '#1A1A1A',
    '--bg-surface': '#222222',
    '--text-primary': '#FFFFFF',
    '--text-secondary': '#CCCCCC',
    '--success': '#2ED573',
    '--warning': '#FFAB00',
    '--error': '#FF4757',
    '--border': '#333333',
  },
  custom: {
    // Solo para Enterprise, los colores se establecen dinámicamente
    '--primary': '#DE350D',
    '--primary-dark': '#B22A0A',
    '--accent': '#6347FF',
    '--accent-light': '#8B6FFF',
    '--bg-dark': '#0D0D0D',
    '--bg-card': '#161616',
    '--bg-surface': '#1E1E1E',
    '--text-primary': '#FFFFFF',
    '--text-secondary': '#A0A0A0',
    '--success': '#2ED573',
    '--warning': '#FFA502',
    '--error': '#FF4757',
    '--border': '#2A2A2A',
  },
};
